---
# tasks file for swarm-manager
- name: determine swarm status
  shell: >
    docker info | egrep '^Swarm: ' | cut -d ' ' -f2
  register: swarm_status

- name: create swarm_manager_running group
  add_host:
    hostname: "{{ item }}"
    groups: swarm_manager_running
  with_items: "{{ play_hosts }}"
  when: "'active' in swarm_status.stdout_lines"
  run_once: true

- name: create swarm_manager_not_running group
  add_host:
    hostname: "{{ item }}"
    groups: swarm_manager_not_running
  with_items: "{{ play_hosts }}"
  when: "'active' not in swarm_status.stdout_lines"
  run_once: true
