global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "targets.rules"
  - "host.rules"
  - "containers.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: 
{% for host in groups['worker']%}
        - '{{ hostvars[host].inventory_hostname }}:9100'
{% endfor %}
{% for host in groups['master']%}
        - '{{ hostvars[host].inventory_hostname }}:9100'
{% endfor %}

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: 
{% for host in groups['worker']%}
        - '{{ hostvars[host].inventory_hostname }}:8080'
{% endfor %}
{% for host in groups['master']%}
        - '{{ hostvars[host].inventory_hostname }}:8080'
{% endfor %}

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
