---
# tasks file for setup-swarm
- name: retrieve swarm manager token
  shell: docker swarm join-token -q manager
  register: swarm_manager_token

- name: retrieve swarm worker token
  shell: docker swarm join-token -q worker
  register: swarm_worker_token

- name: populate list of manager ips
  add_host:
    hostname: "{{ hostvars[item]['ansible_' + iface]['ipv4']['address'] }}"
    groups: swarm_manager_ips
  with_items: "{{ play_hosts }}"
